[server]
headless = true
address = "0.0.0.0"
port = 5000

[theme]
primaryColor = "#4e79a7"
backgroundColor = "#0E1117"
secondaryBackgroundColor = "#1A1D24"
textColor = "#FAFAFA"
font = "sans serif"

[global]
showWarningOnDirectExecution = false